"""empty message

Revision ID: 89207b51b3df
Revises: e5cdf44bc529
Create Date: 2022-01-23 21:13:20.276158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89207b51b3df'
down_revision = 'e5cdf44bc529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'user_id')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=80), nullable=False))
    op.add_column('post', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
